### ISSUE TITLE
Robustness and minor optimization

### ISSUE THREAD

**Issue by RobTillaart** [madhephaestus/ESP32AnalogRead#1]
The code will give a problem if the user calls readVoltage() before the call of attach().

solution 1: move pin and channel assignment to constructor.
solution 2: have a boolean flag that indicated that the object is properly attached/ assigned/ configured

solution 1 could look like this, given an optional parameter, with a default value of pin = 0.
```
ESP32AnalogRead(int pin = 0) { attach(pin); };
```

you could parameterize the constants like ADC_WIDTH_12Bit etc in a similar way, with a default value. Would make the class friendly for beginner and flexible for advanced proggers.

Finally a minor optimization as multiplication tends to be faster for float. 
see https://blog.classycode.com/esp32-floating-point-performance-6e9f6f567a69
```
float ESP32AnalogRead::readVoltage() { return readMiliVolts() * 0.001; };
```

**Comment by madhephaestus** [comment]
Ill take a look at this, thanks for looking at my code!

**Comment by madhephaestus** [comment]
I added your suggestions.
