### ISSUE TITLE
last line in methoc readMiliVolts appears to have a bug

### ISSUE THREAD

**Issue by dl8555** [madhephaestus/ESP32AnalogRead#3]
The line "return voltage - 50;" appears to introduce a 50 millivolt error. When an precise voltage is input to ADC the results returned by voltage alone (without "- 50") are accurate.

Otherwise the code is very functional

**Comment by madhephaestus** [comment]
well thats annoying, i needed that 50mv offset to bring it in line with my DMM. I wonder where the error really is, maybe my DMM is off by 50mv...

Can you tell me how you measured "precise" in your experimental setup?

**Comment by dl8555** [comment]
Hello Kevin,

First indication was a precision thermistor circuit, in a precise temperature, with precise temperature equations were providing incorrect results. 

The circuit is relatively high impedance and I am unsure of the ADC input impedance. I any case the high impedance would reduce what the ADC sees.  So impedance was my first suspicion, until I saw the "- 50" in the code.  Removing it brought the temperature calculated from the ADC voltage into alignment.

FYI, voltage at ADC was in the 700 millivolt range for temperature measurement.

Then I used a previously calibrated (but cal is expired) DMM to measure a DC supply that was used as the ADC input.  The DC supply  removes impedance issues.  Again "-50" seemed to be inducing an error.

Before you change the code, let me add some DC filtering and collect a larger sample of voltage readings over a wider range.

Will get back to you in a few days.

Thanks for the code and the support!

Dan

**Comment by madhephaestus** [comment]
Im starting to think maybe my ESP's calibration fuess are the issue...

**Comment by dl8555** [comment]
I will take some data from each of my 3 ESP32 modules...

**Comment by madhephaestus** [comment]
this is fixed in 0.1.1
