### ISSUE TITLE
fatal error: esp_adc_cal.h: No such file or directory

### ISSUE THREAD

**Issue by magnetophon** [madhephaestus/ESP32AnalogRead#5]
When I try to compile https://github.com/madhephaestus/ESP32AnalogRead/blob/master/examples/ESP32AnalogReadTest/ESP32AnalogReadTest.ino on an NodeMCU, the arduino IDE complains that it can't find the file included in https://github.com/madhephaestus/ESP32AnalogRead/blob/master/ESP32AnalogRead.h#L3

I'm pretty new to this and have no idea how to troobleshoot.
Thanks for any help!

**Comment by madhephaestus** [comment]
The NodeMCU is an esp8266, not an ESP32. This library only supports the ESP32 core, and the esp8266 is a very different processor.

**Comment by magnetophon** [comment]
Oh, duh.

Sorry for the noise!

**Comment by madhephaestus** [comment]
No worries, good luck with your project!
